// GENERATED by tool/gen_ui_assets.dart — do not edit by hand.
// Run `dart run tool/gen_ui_assets.dart` after changing assets/.
//
// Paths for the redesigned UI. Render every one through AppImage
// (core/app_image.dart) so a missing file degrades to a themed
// fallback instead of a broken box.
library;

abstract final class UiAssets {
  static const String aiAssistantAvatar = 'assets/images/ai/ai-assistant-avatar@3x.png';
  static const String aiHologramDogCat = 'assets/images/ai/ai-hologram-dog-cat@3x.png';
  static const String aiLoadingScanRing = 'assets/images/ai/ai-loading-scan-ring@3x.png';
  static const String aiOrbitalRingNodes = 'assets/images/ai/ai-orbital-ring-nodes@3x.png';
  static const String aiRobotMascotNeon = 'assets/images/ai/ai-robot-mascot-neon@3x.png';
  static const String aiScanHudDog = 'assets/images/ai/ai-scan-hud-dog@3x.webp';
  static const String avtCommunity01 = 'assets/images/avatars/avt-community-01@3x.webp';
  static const String avtCommunity02 = 'assets/images/avatars/avt-community-02@3x.webp';
  static const String avtCommunity03 = 'assets/images/avatars/avt-community-03@3x.webp';
  static const String avtCommunity04 = 'assets/images/avatars/avt-community-04@3x.webp';
  static const String avtCommunity05 = 'assets/images/avatars/avt-community-05@3x.webp';
  static const String avtCommunity06 = 'assets/images/avatars/avt-community-06@3x.webp';
  static const String avtMap01 = 'assets/images/avatars/avt-map-01@3x.webp';
  static const String avtMap02 = 'assets/images/avatars/avt-map-02@3x.webp';
  static const String avtMap03 = 'assets/images/avatars/avt-map-03@3x.webp';
  static const String avtMap04 = 'assets/images/avatars/avt-map-04@3x.webp';
  static const String avtSocialProof01 = 'assets/images/avatars/avt-social-proof-01@3x.webp';
  static const String avtSocialProof02 = 'assets/images/avatars/avt-social-proof-02@3x.webp';
  static const String avtSocialProof03 = 'assets/images/avatars/avt-social-proof-03@3x.webp';
  static const String avtSocialProof04 = 'assets/images/avatars/avt-social-proof-04@3x.webp';
  static const String avtUserFemale = 'assets/images/avatars/avt-user-female@3x.webp';
  static const String avtUserMale = 'assets/images/avatars/avt-user-male@3x.webp';
  static const String avtVetFemale = 'assets/images/avatars/avt-vet-female@3x.webp';
  static const String bdg247 = 'assets/badges/bdg-24-7@3x.png';
  static const String bdgAchvCalorieHunter = 'assets/badges/achievements/bdg-achv-calorie-hunter@3x.png';
  static const String bdgAchvCalorieHunterLocked = 'assets/badges/achievements/bdg-achv-calorie-hunter-locked@3x.png';
  static const String bdgAchvDistance50km = 'assets/badges/achievements/bdg-achv-distance-50km@3x.png';
  static const String bdgAchvDistance50kmLocked = 'assets/badges/achievements/bdg-achv-distance-50km-locked@3x.png';
  static const String bdgAchvEarlyBird = 'assets/badges/achievements/bdg-achv-early-bird@3x.png';
  static const String bdgAchvEarlyBirdLocked = 'assets/badges/achievements/bdg-achv-early-bird-locked@3x.png';
  static const String bdgAchvFirst10Walks = 'assets/badges/achievements/bdg-achv-first-10-walks@3x.png';
  static const String bdgAchvFirst10WalksLocked = 'assets/badges/achievements/bdg-achv-first-10-walks-locked@3x.png';
  static const String bdgAchvLockedPadlock = 'assets/badges/achievements/bdg-achv-locked-padlock@3x.png';
  static const String bdgAchvMarathonPaw = 'assets/badges/achievements/bdg-achv-marathon-paw@3x.png';
  static const String bdgAchvMarathonPawLocked = 'assets/badges/achievements/bdg-achv-marathon-paw-locked@3x.png';
  static const String bdgAchvWeekStreak = 'assets/badges/achievements/bdg-achv-week-streak@3x.png';
  static const String bdgAchvWeekStreakLocked = 'assets/badges/achievements/bdg-achv-week-streak-locked@3x.png';
  static const String bdgAwardRosette = 'assets/badges/bdg-award-rosette@3x.png';
  static const String bdgHexFrameLocked = 'assets/badges/achievements/bdg-hex-frame-locked@3x.png';
  static const String bdgHexFrameUnlocked = 'assets/badges/achievements/bdg-hex-frame-unlocked@3x.png';
  static const String bdgHighlightCrown = 'assets/badges/bdg-highlight-crown@3x.png';
  static const String bdgTopContributor = 'assets/badges/bdg-top-contributor@3x.png';
  static const String bdgVerifiedBlue = 'assets/badges/bdg-verified-blue@3x.png';
  static const String bdgVerifiedLime = 'assets/badges/bdg-verified-lime@3x.png';
  static const String brdAppIcon1024 = 'assets/brand/logo/brd-app-icon-1024.png';
  static const String brdLogoLockupHorizontal = 'assets/brand/logo/brd-logo-lockup-horizontal@3x.png';
  static const String brdLogoMark = 'assets/brand/logo/brd-logo-mark@3x.png';
  static const String brdPushIcon = 'assets/brand/logo/brd-push-icon@3x.png';
  static const String brdScriptBestLife = 'assets/brand/logo/brd-script-best-life@3x.png';
  static const String breCategoryAll = 'assets/images/breeds/bre-category-all@3x.webp';
  static const String breCategoryBird = 'assets/images/breeds/bre-category-bird@3x.webp';
  static const String breCategoryCat = 'assets/images/breeds/bre-category-cat@3x.webp';
  static const String breCategoryDog = 'assets/images/breeds/bre-category-dog@3x.webp';
  static const String breCategoryRabbit = 'assets/images/breeds/bre-category-rabbit@3x.webp';
  static const String breCategoryReptile = 'assets/images/breeds/bre-category-reptile@3x.webp';
  static const String breGoldenRetrieverHero = 'assets/images/breeds/bre-golden-retriever-hero@3x.webp';
  static const String breSimilarChesapeake = 'assets/images/breeds/bre-similar-chesapeake@3x.webp';
  static const String breSimilarFlatcoat = 'assets/images/breeds/bre-similar-flatcoat@3x.webp';
  static const String breSimilarLabrador = 'assets/images/breeds/bre-similar-labrador@3x.webp';
  static const String breSimilarToller = 'assets/images/breeds/bre-similar-toller@3x.webp';
  static const String cmnAgilityJump = 'assets/images/community/cmn-agility-jump@3x.webp';
  static const String cmnEditorialHotWeather = 'assets/images/community/cmn-editorial-hot-weather@3x.webp';
  static const String cmnPostPromenade01 = 'assets/images/community/cmn-post-promenade-01@3x.webp';
  static const String cmnPostPromenade02 = 'assets/images/community/cmn-post-promenade-02@3x.webp';
  static const String cmnPostPromenade03 = 'assets/images/community/cmn-post-promenade-03@3x.webp';
  static const String emgBeaconSiren = 'assets/images/emergency/emg-beacon-siren@3x.png';
  static const String emgCallPhoneRings = 'assets/images/emergency/emg-call-phone-rings@3x.png';
  static const String emgClinicExterior01 = 'assets/images/emergency/emg-clinic-exterior-01@3x.webp';
  static const String emgClinicExterior02 = 'assets/images/emergency/emg-clinic-exterior-02@3x.webp';
  static const String emgClinicExterior03 = 'assets/images/emergency/emg-clinic-exterior-03@3x.webp';
  static const String emgCompareStreams = 'assets/images/emergency/emg-compare-streams@3x.png';
  static const String emgDogLesionClinical = 'assets/images/emergency/emg-dog-lesion-clinical@3x.webp';
  static const String emgFirstaidBanner = 'assets/images/emergency/emg-firstaid-banner@3x.webp';
  static const String emgKitStilllife = 'assets/images/emergency/emg-kit-stilllife@3x.png';
  static const String emgMappinClinic = 'assets/images/emergency/emg-mappin-clinic@3x.png';
  static const String emgShieldAlert = 'assets/images/emergency/emg-shield-alert@3x.png';
  static const String icBenefitBetterCare = 'assets/icons/core/ic-benefit-better-care.png';
  static const String icBenefitFamilySharing = 'assets/icons/core/ic-benefit-family-sharing.png';
  static const String icBenefitFreeTrial = 'assets/icons/core/ic-benefit-free-trial.png';
  static const String icBenefitMoneyBack = 'assets/icons/core/ic-benefit-money-back.png';
  static const String icBenefitMoreInsights = 'assets/icons/core/ic-benefit-more-insights.png';
  static const String icBenefitPeaceOfMind = 'assets/icons/core/ic-benefit-peace-of-mind.png';
  static const String icBenefitSaveTime = 'assets/icons/core/ic-benefit-save-time.png';
  static const String icBenefitSecurePrivate = 'assets/icons/core/ic-benefit-secure-private.png';
  static const String icBringFoodTreats = 'assets/icons/core/ic-bring-food-treats.png';
  static const String icBringMedications = 'assets/icons/core/ic-bring-medications.png';
  static const String icBringPhotosVideos = 'assets/icons/core/ic-bring-photos-videos.png';
  static const String icBringPreviousRecords = 'assets/icons/core/ic-bring-previous-records.png';
  static const String icBringSampleCup = 'assets/icons/core/ic-bring-sample-cup.png';
  static const String icSpeciesCatBadge = 'assets/icons/core/ic-species-cat-badge@3x.png';
  static const String icSpeciesDogBadge = 'assets/icons/core/ic-species-dog-badge@3x.png';
  static const String icSpeciesOtherBadge = 'assets/icons/core/ic-species-other-badge@3x.png';
  static const String illDoodleClipboard = 'assets/illustrations/doodles/ill-doodle-clipboard@3x.png';
  static const String illDoodleDogScale = 'assets/illustrations/doodles/ill-doodle-dog-scale@3x.png';
  static const String illDoodleDogSittingHeart = 'assets/illustrations/doodles/ill-doodle-dog-sitting-heart@3x.png';
  static const String illDoodleDogfaceHeart = 'assets/illustrations/doodles/ill-doodle-dogface-heart@3x.png';
  static const String illDoodlePuppyHeartBubble = 'assets/illustrations/doodles/ill-doodle-puppy-heart-bubble@3x.png';
  static const String illDoodlePuppyShield = 'assets/illustrations/doodles/ill-doodle-puppy-shield@3x.png';
  static const String illDoodleRunningDogTrail = 'assets/illustrations/doodles/ill-doodle-running-dog-trail@3x.png';
  static const String illDoodleVetCatDog = 'assets/illustrations/doodles/ill-doodle-vet-cat-dog@3x.png';
  static const String illPawtrailDashed = 'assets/illustrations/doodles/ill-pawtrail-dashed@3x.png';
  static const String infAnatomyEar = 'assets/illustrations/infographics/inf-anatomy-ear@3x.webp';
  static const String infAnatomyEye = 'assets/illustrations/infographics/inf-anatomy-eye@3x.webp';
  static const String infAnatomyMouth = 'assets/illustrations/infographics/inf-anatomy-mouth@3x.webp';
  static const String infAnatomyNose = 'assets/illustrations/infographics/inf-anatomy-nose@3x.webp';
  static const String infClinicalPawRedness = 'assets/illustrations/infographics/inf-clinical-paw-redness@3x.webp';
  static const String infPhotoqualityBlurry = 'assets/illustrations/infographics/inf-photoquality-blurry@3x.webp';
  static const String infPhotoqualityDark = 'assets/illustrations/infographics/inf-photoquality-dark@3x.webp';
  static const String infPhotoqualityGood = 'assets/illustrations/infographics/inf-photoquality-good@3x.webp';
  static const String mapCommunityNeighbourhood = 'assets/images/maps/map-community-neighbourhood@3x.webp';
  static const String mapEmergencyClinics = 'assets/images/maps/map-emergency-clinics@3x.webp';
  static const String mapMemoryLocation = 'assets/images/maps/map-memory-location@3x.webp';
  static const String mapPinUser = 'assets/images/maps/map-pin-user@3x.png';
  static const String mapRouteThumb01 = 'assets/images/maps/map-route-thumb-01@3x.webp';
  static const String mapRouteThumb02 = 'assets/images/maps/map-route-thumb-02@3x.webp';
  static const String mapRouteThumb03 = 'assets/images/maps/map-route-thumb-03@3x.webp';
  static const String mapWalkRouteLive = 'assets/images/maps/map-walk-route-live@3x.webp';
  static const String onbCollisionNotequal = 'assets/images/onboarding/devices/onb-collision-notequal@3x.png';
  static const String onbDeviceIphoneFrame = 'assets/images/onboarding/devices/onb-device-iphone-frame@3x.png';
  static const String onbGlyphBellNeon = 'assets/images/onboarding/devices/onb-glyph-bell-neon@3x.png';
  static const String onbGlyphBrainNeon = 'assets/images/onboarding/devices/onb-glyph-brain-neon@3x.png';
  static const String onbGlyphDiaryNeon = 'assets/images/onboarding/devices/onb-glyph-diary-neon@3x.png';
  static const String onbGlyphDiaryPawCyan = 'assets/images/onboarding/devices/onb-glyph-diary-paw-cyan@3x.png';
  static const String onbHeroDogCatHalo = 'assets/images/onboarding/devices/onb-hero-dog-cat-halo@3x.webp';
  static const String onbHeroDogKittenCelebration = 'assets/images/onboarding/devices/onb-hero-dog-kitten-celebration@3x.webp';
  static const String onbHeroDogKittenCutout = 'assets/images/onboarding/devices/onb-hero-dog-kitten-cutout@3x.webp';
  static const String onbHeroDuoNeon = 'assets/images/onboarding/firstrun/onb-hero-duo-neon.webp';
  static const String onbHeroPuppyKittenBlanket = 'assets/images/onboarding/devices/onb-hero-puppy-kitten-blanket@3x.webp';
  static const String onbHeroPuppyKittenSeated = 'assets/images/onboarding/devices/onb-hero-puppy-kitten-seated@3x.webp';
  static const String onbHeroPuppyKittenSplash = 'assets/images/onboarding/devices/onb-hero-puppy-kitten-splash@3x.webp';
  static const String onbLogoPawdoc = 'assets/images/onboarding/firstrun/onb-logo-pawdoc.webp';
  static const String onbShieldPawTeal3d = 'assets/images/onboarding/devices/onb-shield-paw-teal-3d@3x.png';
  static const String onbUploadCameraRing = 'assets/images/onboarding/devices/onb-upload-camera-ring@3x.png';
  static const String petBuddyAvatar = 'assets/images/pets/cast/pet-buddy-avatar@3x.webp';
  static const String petBuddyGrassGoldenHour = 'assets/images/pets/cast/pet-buddy-grass-golden-hour@3x.webp';
  static const String petBuddyHeroCutout = 'assets/images/pets/cast/pet-buddy-hero-cutout@3x.webp';
  static const String petBuddyParkPortrait = 'assets/images/pets/cast/pet-buddy-park-portrait@3x.webp';
  static const String petBuddyShieldComposite = 'assets/images/pets/cast/pet-buddy-shield-composite@3x.png';
  static const String petCocoLopAvatar = 'assets/images/pets/cast/pet-coco-lop-avatar@3x.webp';
  static const String petLunaRabbitAvatar = 'assets/images/pets/cast/pet-luna-rabbit-avatar@3x.webp';
  static const String petLunaRetrieverPortrait = 'assets/images/pets/cast/pet-luna-retriever-portrait@3x.webp';
  static const String petMiloShorthairAvatar = 'assets/images/pets/cast/pet-milo-shorthair-avatar@3x.webp';
  static const String petMiloTabbyAvatar = 'assets/images/pets/cast/pet-milo-tabby-avatar@3x.webp';
  static const String petSpeciesBird = 'assets/images/pets/cast/pet-species-bird@3x.webp';
  static const String petSpeciesCat = 'assets/images/pets/cast/pet-species-cat@3x.webp';
  static const String petSpeciesDog = 'assets/images/pets/cast/pet-species-dog@3x.webp';
  static const String petSpeciesGuineaPig = 'assets/images/pets/cast/pet-species-guinea_pig@3x.webp';
  static const String petSpeciesOther = 'assets/images/pets/cast/pet-species-other@3x.webp';
  static const String petSpeciesRabbit = 'assets/images/pets/cast/pet-species-rabbit@3x.webp';
  static const String petSpeciesReptile = 'assets/images/pets/cast/pet-species-reptile@3x.webp';
  static const String prm3dAiInsights = 'assets/images/premium/prm-3d-ai-insights@3x.webp';
  static const String prm3dBellPaw = 'assets/images/premium/prm-3d-bell-paw@3x.png';
  static const String prm3dCrownPaw = 'assets/images/premium/prm-3d-crown-paw@3x.png';
  static const String prm3dMultipet = 'assets/images/premium/prm-3d-multipet@3x.png';
  static const String prm3dPdfReport = 'assets/images/premium/prm-3d-pdf-report@3x.png';
  static const String prm3dShieldLock = 'assets/images/premium/prm-3d-shield-lock@3x.png';
  static const String prm3dShieldPaw = 'assets/images/premium/prm-3d-shield-paw@3x.png';
  static const String prm3dSmartAlerts = 'assets/images/premium/prm-3d-smart-alerts@3x.png';
  static const String prm3dStorage = 'assets/images/premium/prm-3d-storage@3x.png';
  static const String prm3dUsageGauge = 'assets/images/premium/prm-3d-usage-gauge@3x.webp';
  static const String prm3dVetChat = 'assets/images/premium/prm-3d-vet-chat@3x.png';
  static const String prmCrownLime = 'assets/images/premium/prm-crown-lime@3x.png';
  static const String prmHeroDogCatDuo = 'assets/images/premium/prm-hero-dog-cat-duo@3x.webp';

  /// 8 entries, keyed by slug.
  static const Map<String, String> actionSet = {
    'copy': 'assets/icons/actions/ic-act-copy.png',
    'helpful': 'assets/icons/actions/ic-act-helpful.png',
    'notHelpful': 'assets/icons/actions/ic-act-not-helpful.png',
    'regenerate': 'assets/icons/actions/ic-act-regenerate.png',
    'reminder': 'assets/icons/actions/ic-act-reminder.png',
    'report': 'assets/icons/actions/ic-act-report.png',
    'saveDiary': 'assets/icons/actions/ic-act-save-diary.png',
    'share': 'assets/icons/actions/ic-act-share.png',
  };

  static String? action(String key) => actionSet[key];

  /// 12 entries, keyed by slug.
  static const Map<String, String> anatomySet = {
    'bloatStomach': 'assets/icons/anatomy/ic-anat-bloat-stomach.png',
    'brain': 'assets/icons/anatomy/ic-anat-brain.png',
    'cancerRibbon': 'assets/icons/anatomy/ic-anat-cancer-ribbon.png',
    'elbowDysplasia': 'assets/icons/anatomy/ic-anat-elbow-dysplasia.png',
    'eyesEarsNose': 'assets/icons/anatomy/ic-anat-eyes-ears-nose.png',
    'heartAnatomical': 'assets/icons/anatomy/ic-anat-heart-anatomical.png',
    'hipDysplasia': 'assets/icons/anatomy/ic-anat-hip-dysplasia.png',
    'joint': 'assets/icons/anatomy/ic-anat-joint.png',
    'kidney': 'assets/icons/anatomy/ic-anat-kidney.png',
    'liver': 'assets/icons/anatomy/ic-anat-liver.png',
    'lungs': 'assets/icons/anatomy/ic-anat-lungs.png',
    'skinCoat': 'assets/icons/anatomy/ic-anat-skin-coat.png',
  };

  static String? anatomy(String key) => anatomySet[key];

  /// 12 entries, keyed by slug.
  static const Map<String, String> breedCareSet = {
    'barking': 'assets/icons/breed-care/ic-care-barking.png',
    'birthdayCake': 'assets/icons/breed-care/ic-care-birthday-cake.png',
    'exercise': 'assets/icons/breed-care/ic-care-exercise.png',
    'grooming': 'assets/icons/breed-care/ic-care-grooming.png',
    'intelligence': 'assets/icons/breed-care/ic-care-intelligence.png',
    'lifespan': 'assets/icons/breed-care/ic-care-lifespan.png',
    'playtimeBall': 'assets/icons/breed-care/ic-care-playtime-ball.png',
    'shedding': 'assets/icons/breed-care/ic-care-shedding.png',
    'size': 'assets/icons/breed-care/ic-care-size.png',
    'trainability': 'assets/icons/breed-care/ic-care-trainability.png',
    'vacationSuitcase': 'assets/icons/breed-care/ic-care-vacation-suitcase.png',
    'vetVisitSearch': 'assets/icons/breed-care/ic-care-vet-visit-search.png',
  };

  static String? breedCare(String key) => breedCareSet[key];

  /// 8 entries, keyed by slug.
  static const Map<String, String> firstAidSet = {
    'bleeding': 'assets/icons/firstaid/ic-fa-bleeding@3x.png',
    'choking': 'assets/icons/firstaid/ic-fa-choking@3x.png',
    'cuts': 'assets/icons/firstaid/ic-fa-cuts@3x.png',
    'eyeInjury': 'assets/icons/firstaid/ic-fa-eye-injury@3x.png',
    'heatstroke': 'assets/icons/firstaid/ic-fa-heatstroke@3x.png',
    'other': 'assets/icons/firstaid/ic-fa-other@3x.png',
    'poisoning': 'assets/icons/firstaid/ic-fa-poisoning@3x.png',
    'vomiting': 'assets/icons/firstaid/ic-fa-vomiting@3x.png',
  };

  static String? firstAid(String key) => firstAidSet[key];

  /// 4 entries, keyed by slug.
  static const Map<String, String> medicationSet = {
    'chewable': 'assets/icons/medication/ic-med-chewable@3x.png',
    'liquid': 'assets/icons/medication/ic-med-liquid@3x.png',
    'tablet': 'assets/icons/medication/ic-med-tablet@3x.png',
    'topical': 'assets/icons/medication/ic-med-topical@3x.png',
  };

  static String? medication(String key) => medicationSet[key];

  /// 24 entries, keyed by slug.
  static const Map<String, String> memorySet = {
    'n01': 'assets/images/memories/mem-buddy-01@3x.webp',
    'n02': 'assets/images/memories/mem-buddy-02@3x.webp',
    'n03': 'assets/images/memories/mem-buddy-03@3x.webp',
    'n04': 'assets/images/memories/mem-buddy-04@3x.webp',
    'n05': 'assets/images/memories/mem-buddy-05@3x.webp',
    'n06': 'assets/images/memories/mem-buddy-06@3x.webp',
    'n07': 'assets/images/memories/mem-buddy-07@3x.webp',
    'n08': 'assets/images/memories/mem-buddy-08@3x.webp',
    'n09': 'assets/images/memories/mem-buddy-09@3x.webp',
    'n10': 'assets/images/memories/mem-buddy-10@3x.webp',
    'n11': 'assets/images/memories/mem-buddy-11@3x.webp',
    'n12': 'assets/images/memories/mem-buddy-12@3x.webp',
    'n13': 'assets/images/memories/mem-buddy-13@3x.webp',
    'n14': 'assets/images/memories/mem-buddy-14@3x.webp',
    'n15': 'assets/images/memories/mem-buddy-15@3x.webp',
    'n16': 'assets/images/memories/mem-buddy-16@3x.webp',
    'n17': 'assets/images/memories/mem-buddy-17@3x.webp',
    'n18': 'assets/images/memories/mem-buddy-18@3x.webp',
    'n19': 'assets/images/memories/mem-buddy-19@3x.webp',
    'n20': 'assets/images/memories/mem-buddy-20@3x.webp',
    'n21': 'assets/images/memories/mem-buddy-21@3x.webp',
    'n22': 'assets/images/memories/mem-buddy-22@3x.webp',
    'n23': 'assets/images/memories/mem-buddy-23@3x.webp',
    'n24': 'assets/images/memories/mem-buddy-24@3x.webp',
  };

  static String? memory(String key) => memorySet[key];

  /// 6 entries, keyed by slug.
  static const Map<String, String> notificationSet = {
    'community': 'assets/icons/notifications/ic-notif-community@3x.png',
    'healthAlerts': 'assets/icons/notifications/ic-notif-health-alerts@3x.png',
    'healthReminders': 'assets/icons/notifications/ic-notif-health-reminders@3x.png',
    'promotions': 'assets/icons/notifications/ic-notif-promotions@3x.png',
    'tipsEducation': 'assets/icons/notifications/ic-notif-tips-education@3x.png',
    'vetAppUpdates': 'assets/icons/notifications/ic-notif-vet-app-updates@3x.png',
  };

  static String? notification(String key) => notificationSet[key];

  /// 8 entries, keyed by slug.
  static const Map<String, String> recordSet = {
    'aiAnalysis': 'assets/icons/records/ic-rec-ai-analysis.png',
    'labResult': 'assets/icons/records/ic-rec-lab-result.png',
    'medication': 'assets/icons/records/ic-rec-medication.png',
    'memory': 'assets/icons/records/ic-rec-memory.png',
    'note': 'assets/icons/records/ic-rec-note.png',
    'vaccination': 'assets/icons/records/ic-rec-vaccination.png',
    'vetVisit': 'assets/icons/records/ic-rec-vet-visit.png',
    'weight': 'assets/icons/records/ic-rec-weight.png',
  };

  static String? record(String key) => recordSet[key];

  /// 24 entries, keyed by slug.
  static const Map<String, String> symptomSet = {
    'appetiteLoss': 'assets/icons/symptoms/ic-symptom-appetite-loss.png',
    'badBreath': 'assets/icons/symptoms/ic-symptom-bad-breath.png',
    'behaviourChange': 'assets/icons/symptoms/ic-symptom-behaviour-change.png',
    'bleeding': 'assets/icons/symptoms/ic-symptom-bleeding.png',
    'bloating': 'assets/icons/symptoms/ic-symptom-bloating.png',
    'breathingDifficulty': 'assets/icons/symptoms/ic-symptom-breathing-difficulty.png',
    'coughing': 'assets/icons/symptoms/ic-symptom-coughing.png',
    'diarrhea': 'assets/icons/symptoms/ic-symptom-diarrhea.png',
    'disorientation': 'assets/icons/symptoms/ic-symptom-disorientation.png',
    'earProblem': 'assets/icons/symptoms/ic-symptom-ear-problem.png',
    'excessiveThirst': 'assets/icons/symptoms/ic-symptom-excessive-thirst.png',
    'eyeDischarge': 'assets/icons/symptoms/ic-symptom-eye-discharge.png',
    'hairLoss': 'assets/icons/symptoms/ic-symptom-hair-loss.png',
    'itching': 'assets/icons/symptoms/ic-symptom-itching.png',
    'lethargy': 'assets/icons/symptoms/ic-symptom-lethargy.png',
    'limping': 'assets/icons/symptoms/ic-symptom-limping.png',
    'painResponse': 'assets/icons/symptoms/ic-symptom-pain-response.png',
    'seizure': 'assets/icons/symptoms/ic-symptom-seizure.png',
    'skinIrritation': 'assets/icons/symptoms/ic-symptom-skin-irritation.png',
    'sneezing': 'assets/icons/symptoms/ic-symptom-sneezing.png',
    'swelling': 'assets/icons/symptoms/ic-symptom-swelling.png',
    'urinationChange': 'assets/icons/symptoms/ic-symptom-urination-change.png',
    'vomiting': 'assets/icons/symptoms/ic-symptom-vomiting.png',
    'weightLoss': 'assets/icons/symptoms/ic-symptom-weight-loss.png',
  };

  static String? symptom(String key) => symptomSet[key];

  /// 8 entries, keyed by slug.
  static const Map<String, String> vaccineSet = {
    'bordetella': 'assets/icons/vaccines/ic-vax-bordetella@3x.png',
    'dhpp': 'assets/icons/vaccines/ic-vax-dhpp@3x.png',
    'distemper': 'assets/icons/vaccines/ic-vax-distemper@3x.png',
    'influenza': 'assets/icons/vaccines/ic-vax-influenza@3x.png',
    'leptospirosis': 'assets/icons/vaccines/ic-vax-leptospirosis@3x.png',
    'lyme': 'assets/icons/vaccines/ic-vax-lyme@3x.png',
    'parvovirus': 'assets/icons/vaccines/ic-vax-parvovirus@3x.png',
    'rabies': 'assets/icons/vaccines/ic-vax-rabies@3x.png',
  };

  static String? vaccine(String key) => vaccineSet[key];

  /// 10 entries, keyed by slug.
  static const Map<String, String> vitalSet = {
    'activityLevel': 'assets/icons/vitals/ic-vital-activity-level.png',
    'activityLevelEcg': 'assets/icons/vitals/ic-vital-activity-level-ecg.png',
    'respiratoryRate': 'assets/icons/vitals/ic-vital-respiratory-rate.png',
    'respiratoryRateEcg': 'assets/icons/vitals/ic-vital-respiratory-rate-ecg.png',
    'restingHeartRate': 'assets/icons/vitals/ic-vital-resting-heart-rate.png',
    'restingHeartRateEcg': 'assets/icons/vitals/ic-vital-resting-heart-rate-ecg.png',
    'restingTime': 'assets/icons/vitals/ic-vital-resting-time.png',
    'restingTimeEcg': 'assets/icons/vitals/ic-vital-resting-time-ecg.png',
    'temperature': 'assets/icons/vitals/ic-vital-temperature.png',
    'temperatureEcg': 'assets/icons/vitals/ic-vital-temperature-ecg.png',
  };

  static String? vital(String key) => vitalSet[key];

  /// 8 entries, keyed by slug.
  static const Map<String, String> weatherSet = {
    'cloud': 'assets/icons/weather-3d/ic-wx-cloud@3x.png',
    'cloudHeavyRain': 'assets/icons/weather-3d/ic-wx-cloud-heavy-rain@3x.png',
    'cloudRain': 'assets/icons/weather-3d/ic-wx-cloud-rain@3x.png',
    'snow': 'assets/icons/weather-3d/ic-wx-snow@3x.png',
    'sun': 'assets/icons/weather-3d/ic-wx-sun@3x.png',
    'sunCloud': 'assets/icons/weather-3d/ic-wx-sun-cloud@3x.png',
    'thunder': 'assets/icons/weather-3d/ic-wx-thunder@3x.png',
    'wind': 'assets/icons/weather-3d/ic-wx-wind@3x.png',
  };

  static String? weather(String key) => weatherSet[key];
}
