import 'package:flutter/material.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

import '../health/health_sections.dart';
import '../theme/design_tokens.dart';
import 'emergency_help_screen.dart';
import 'emergency_sections.dart';
import 'first_aid.dart';

/// Mockup `first_aid_guide`, over the bundled cards in `first_aid.dart`.
///
/// Search, the category rail, the hero banner, the topic list, the reminder
/// card and the red call band — the reference's composition, carrying only
/// content that exists offline.
///
/// **What the reference draws that this screen does not, and why.**
///
///  * **"Not sure what's wrong? … our AI Triager will guide you. [✨ Start AI
///    Triage] ✨ AI Powered"** in the hero slot. Review item V-17, CRITICAL
///    against `CLAUDE.md`'s emergency rule: a model-dependent call to action in
///    the first position of the first-aid screen, which must work with the
///    radio off. The banner keeps its geometry and its artwork and carries
///    V-17's approved replacement — *Not sure where to start? / Browse by
///    symptom / Works offline*. The AI check is not being hidden from the
///    product; it is one tap away on Home and in the AI Care tab, where the
///    quota, the override and the action ladder all apply.
///  * **"High Priority" badges** on four of seven rows — see
///    [kFirstAidOrder] for why a severity badge is the wrong instrument here.
///  * **"Most relevant ⌄"** sorting (V-27) — replaced by the fixed order.
///  * **"🕐 6 min" read times** — invented, and a cost signal on a screen where
///    the owner should not be counting. Rows print the card's step count.
///  * **"Call Emergency · Available 24/7"** — PawDoc runs no line and cannot
///    promise a clinic's hours. See [EmergencyCallBand].
///  * **Poisoning, Cuts & Minor Injuries, Vomiting & Diarrhea, Eye Injuries**
///    as cards. PawDoc ships five first-aid cards and this batch wrote no new
///    ones: the content in `first_aid.dart` carries a standing founder gate
///    for veterinary review, and authoring four more sets of clinical
///    instructions to fill a reference's list would walk straight past it.
///    Poisoning is the one of the four with a real answer on this screen
///    already — the poison-control line, which is where that call belongs
///    rather than in a card.
///
/// **The bottom navigation the reference draws is the seventh omission.** This
/// screen is pushed from `EmergencyHelpScreen`, which renders with no
/// `ProviderScope` on purpose — that is how the red path proves it depends on
/// no app state. `PawNavBar` is a `ConsumerWidget`, so carrying it here would
/// have re-introduced the dependency one push down the same journey, and a
/// tab bar under the thumb of someone the app has just escalated is not what
/// that space is for. The whole red path is dependency-free, uniformly.
class FirstAidGuideScreen extends StatefulWidget {
  const FirstAidGuideScreen({super.key});

  @override
  State<FirstAidGuideScreen> createState() => _FirstAidGuideScreenState();
}

class _FirstAidGuideScreenState extends State<FirstAidGuideScreen> {
  final _search = TextEditingController();
  final _searchFocus = FocusNode();

  String _query = '';
  String? _category;

  @override
  void dispose() {
    _search.dispose();
    _searchFocus.dispose();
    super.dispose();
  }

  List<FirstAidTopic> get _visible {
    final ordered = orderedFirstAidTopics();
    final byCategory = _category == null
        ? ordered
        : [
            for (final t in ordered)
              if (t.id == _category) t,
          ];
    return searchFirstAid(byCategory, _query);
  }

  void _openTopic(FirstAidTopic topic) {
    Navigator.of(context).push(
      MaterialPageRoute<void>(builder: (_) => FirstAidScreen(topic: topic)),
    );
  }

  void _showDisclaimer() {
    showModalBottomSheet<void>(
      context: context,
      backgroundColor: Colors.transparent,
      isScrollControlled: true,
      builder: (_) => const HealthSheet(
        title: 'About this guide',
        children: [
          Padding(
            padding: EdgeInsets.fromLTRB(4, 2, 4, 14),
            child: Text(
              'These cards are general first-aid information about emergency '
              'situations. They are not a diagnosis, they are not tailored to '
              'your pet, and following them is never a substitute for seeing a '
              'veterinarian.\n\n'
              'They are stored in the app, so they open with no signal and no '
              'account. Nothing on this screen is generated by AI.\n\n'
              'If you are unsure, treat it as an emergency and get help.',
              style: TextStyle(
                  color: HealthTone.muted, fontSize: 13.5, height: 1.5),
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final topics = _visible;
    return HealthRecordScaffold(
      appBar: PetModuleAppBar(
        title: 'First Aid Guide',
        icon: LucideIcons.shieldPlus,
        subtitle: 'Step-by-step help when it matters.',
        actionsWidth: 116,
        actions: [
          HealthActionPill(
            key: const Key('first_aid_disclaimer'),
            label: 'Disclaimer',
            icon: LucideIcons.info,
            onTap: _showDisclaimer,
          ),
        ],
      ),
      children: [
        gap(2),
        HealthSearchField(
          controller: _search,
          focusNode: _searchFocus,
          autofocus: false,
          fieldKey: const Key('first_aid_search'),
          hint: 'Search a symptom or emergency…',
          onChanged: (v) => setState(() => _query = v),
        ),
        gap(10),
        HealthBleed(
          child: FirstAidCategoryRail(
            topics: orderedFirstAidTopics(),
            selected: _category,
            onSelect: (id) => setState(() => _category = id),
          ),
        ),
        gap(4),
        _StartHereBanner(onBrowse: () => _searchFocus.requestFocus()),
        gap(18),
        const HealthSectionHead(title: 'Common first-aid topics'),
        gap(3),
        const Text(
          'Most time-critical first. This order never changes.',
          style: TextStyle(color: HealthTone.faint, fontSize: 11.5),
        ),
        gap(8),
        Container(
          decoration: BoxDecoration(
            color: HealthTone.card,
            borderRadius: BorderRadius.circular(18),
            border: Border.all(color: Colors.white.withValues(alpha: 0.07)),
          ),
          padding: const EdgeInsets.symmetric(horizontal: 13, vertical: 2),
          child: topics.isEmpty
              ? const Padding(
                  padding: EdgeInsets.symmetric(vertical: 22),
                  child: Text(
                    'No card matches that. The guide ships five cards — clear '
                    'the search to see them, and if your pet is in danger use '
                    'the red buttons below rather than reading on.',
                    key: Key('first_aid_no_match'),
                    textAlign: TextAlign.center,
                    style: TextStyle(
                        color: HealthTone.muted, fontSize: 12.5, height: 1.45),
                  ),
                )
              : Column(
                  children: [
                    for (var i = 0; i < topics.length; i++)
                      FirstAidRow(
                        topic: topics[i],
                        showDivider: i != topics.length - 1,
                        onTap: () => _openTopic(topics[i]),
                      ),
                  ],
                ),
        ),
        gap(14),
        const EmergencyHonestyNote(),
        gap(12),
        const EmergencyCallBand(),
        gap(6),
      ],
    );
  }
}

/// The reference's hero banner, carrying V-17's approved copy.
class _StartHereBanner extends StatelessWidget {
  const _StartHereBanner({required this.onBrowse});

  final VoidCallback onBrowse;

  @override
  Widget build(BuildContext context) {
    const accent = AppColors.lime500;
    return ClipRRect(
      borderRadius: BorderRadius.circular(18),
      child: Stack(
        children: [
          Positioned.fill(
            child: Image.asset(
              'assets/images/emergency/emg-firstaid-banner@3x.webp',
              fit: BoxFit.cover,
              alignment: Alignment.centerRight,
            ),
          ),
          // The artwork's left half is near-black already; the scrim keeps the
          // copy legible over the glow if the crop shifts on a wider screen.
          Positioned.fill(
            child: DecoratedBox(
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.centerLeft,
                  end: Alignment.centerRight,
                  colors: [
                    Colors.black.withValues(alpha: 0.78),
                    Colors.black.withValues(alpha: 0.10),
                  ],
                ),
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.fromLTRB(15, 15, 15, 14),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize: MainAxisSize.min,
              children: [
                const SizedBox(
                  width: 195,
                  child: Text(
                    'Not sure where to start?',
                    style: TextStyle(
                        color: Colors.white,
                        fontSize: 17,
                        height: 1.2,
                        fontWeight: FontWeight.w700),
                  ),
                ),
                const SizedBox(height: 5),
                const SizedBox(
                  width: 195,
                  child: Text(
                    'Find the right first-aid steps by what you can see right '
                    'now.',
                    style: TextStyle(
                        color: Colors.white70, fontSize: 12, height: 1.35),
                  ),
                ),
                const SizedBox(height: 11),
                // The button takes the slack and the badge keeps its size, so
                // a long label ellipsises rather than pushing "Works offline"
                // off the banner. `Flexible` + `Spacer` would have split the
                // row evenly and truncated the button while the badge sat in
                // empty space.
                Row(
                  children: [
                    Expanded(
                      child: Align(
                        alignment: Alignment.centerLeft,
                        child: Material(
                          color: accent,
                          borderRadius: BorderRadius.circular(AppRadius.pill),
                          child: InkWell(
                            key: const Key('first_aid_browse'),
                            onTap: onBrowse,
                            borderRadius: BorderRadius.circular(AppRadius.pill),
                            child: const Padding(
                              padding: EdgeInsets.symmetric(
                                  horizontal: 15, vertical: 9),
                              child: Text('Browse by symptom',
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                  style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 13,
                                      fontWeight: FontWeight.w700)),
                            ),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(width: 10),
                    Container(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 8, vertical: 4),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(AppRadius.pill),
                        color: Colors.black.withValues(alpha: 0.45),
                        border: Border.all(
                            color: accent.withValues(alpha: 0.45)),
                      ),
                      child: const Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Icon(LucideIcons.wifiOff, size: 11, color: accent),
                          SizedBox(width: 4),
                          Text('Works offline',
                              style: TextStyle(
                                  color: accent,
                                  fontSize: 10.5,
                                  fontWeight: FontWeight.w700)),
                        ],
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
