// Regenerates lib/src/theme/ui_assets.dart from what is actually on disk.
//
//   dart run tool/gen_ui_assets.dart
//
// The Phase 0 pipeline (see UI_IMPLEMENTATION_ROADMAP.md §Phase 0) slices the
// generated plates into assets/. This walks the result so the Dart constants
// can never drift from the files: a renamed or deleted asset becomes a compile
// error rather than a runtime grey box.
import 'dart:io';

const _roots = [
  'assets/icons',
  'assets/badges',
  'assets/brand/logo',
  'assets/images',
  'assets/illustrations/doodles',
  'assets/illustrations/infographics',
];

/// Icon families addressed by a runtime key (symptom slugs, weather codes …)
/// get a lookup map instead of 24 individual constants.
const _families = <String, String>{
  'assets/icons/symptoms': 'symptom',
  'assets/icons/anatomy': 'anatomy',
  'assets/icons/vaccines': 'vaccine',
  'assets/icons/firstaid': 'firstAid',
  'assets/icons/actions': 'action',
  'assets/icons/notifications': 'notification',
  'assets/icons/medication': 'medication',
  'assets/icons/weather-3d': 'weather',
  'assets/icons/vitals': 'vital',
  'assets/icons/records': 'record',
  'assets/icons/breed-care': 'breedCare',
  'assets/images/memories': 'memory',
};

String _camel(String s) {
  final parts = s.split(RegExp(r'[-_ ]+')).where((p) => p.isNotEmpty).toList();
  if (parts.isEmpty) return s;
  return parts.first.toLowerCase() +
      parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
}

/// `ic-symptom-ear-problem.png` -> `earProblem`; `mem-buddy-03@3x.webp` -> `n03`
String _key(String file, String prefix) {
  var n = file.replaceAll(RegExp(r'@\d+x'), '');
  n = n.substring(0, n.lastIndexOf('.'));
  if (prefix.isNotEmpty && n.startsWith(prefix)) n = n.substring(prefix.length);
  final c = _camel(n);
  return RegExp(r'^\d').hasMatch(c) ? 'n$c' : c;
}

String _prefixFor(String dir) => switch (dir.split('/').last) {
      'symptoms' => 'ic-symptom-',
      'anatomy' => 'ic-anat-',
      'vaccines' => 'ic-vax-',
      'firstaid' => 'ic-fa-',
      'actions' => 'ic-act-',
      'notifications' => 'ic-notif-',
      'medication' => 'ic-med-',
      'weather-3d' => 'ic-wx-',
      'vitals' => 'ic-vital-',
      'records' => 'ic-rec-',
      'breed-care' => 'ic-care-',
      'memories' => 'mem-buddy-',
      _ => '',
    };

void main() {
  final b = StringBuffer()
    ..writeln('// GENERATED by tool/gen_ui_assets.dart — do not edit by hand.')
    ..writeln('// Run `dart run tool/gen_ui_assets.dart` after changing assets/.')
    ..writeln('//')
    ..writeln('// Paths for the redesigned UI. Render every one through AppImage')
    ..writeln('// (core/app_image.dart) so a missing file degrades to a themed')
    ..writeln('// fallback instead of a broken box.')
    ..writeln('library;')
    ..writeln()
    ..writeln('abstract final class UiAssets {');

  final singles = <String, String>{};
  final familyMaps = <String, Map<String, String>>{};

  for (final root in _roots) {
    final d = Directory(root);
    if (!d.existsSync()) continue;
    for (final e in d.listSync(recursive: true).whereType<File>()) {
      final p = e.path.replaceAll(r'\', '/');
      if (p.contains('/_plates/')) continue;
      final ext = p.substring(p.lastIndexOf('.'));
      if (!const ['.png', '.webp', '.svg'].contains(ext)) continue;

      final dir = p.substring(0, p.lastIndexOf('/'));
      final file = p.substring(p.lastIndexOf('/') + 1);
      final fam = _families[dir];
      if (fam != null) {
        (familyMaps[fam] ??= {})[_key(file, _prefixFor(dir))] = p;
      } else {
        var name = _key(file, '');
        while (singles.containsKey(name)) {
          name = '${name}_';
        }
        singles[name] = p;
      }
    }
  }

  final names = singles.keys.toList()..sort();
  for (final n in names) {
    b.writeln("  static const String $n = '${singles[n]}';");
  }

  for (final fam in familyMaps.keys.toList()..sort()) {
    final m = familyMaps[fam]!;
    final keys = m.keys.toList()..sort();
    b
      ..writeln()
      ..writeln('  /// ${keys.length} entries, keyed by slug.')
      ..writeln('  static const Map<String, String> ${fam}Set = {');
    for (final k in keys) {
      b.writeln("    '$k': '${m[k]}',");
    }
    b
      ..writeln('  };')
      ..writeln()
      ..writeln('  static String? $fam(String key) => ${fam}Set[key];');
  }

  b.writeln('}');
  File('lib/src/theme/ui_assets.dart').writeAsStringSync(b.toString());

  final total = singles.length + familyMaps.values.fold(0, (a, m) => a + m.length);
  stdout.writeln('ui_assets.dart: $total assets '
      '(${singles.length} constants, ${familyMaps.length} families)');
}
