"""/analyze HTTP endpoint.

Internal-only. Required headers:
- ``X-PawDoc-Internal-Token: <secret>`` — shared with the edge function.
- ``X-Request-ID: <uuid>`` — generated by the edge function; bound to logs.

The body is an :class:`AnalysisRequest`. The response is an
:class:`AnalysisResult`. Auth verification, schema validation, and the
internal-token check happen here; the orchestrator handles routing.
"""

from __future__ import annotations

import hmac

from fastapi import APIRouter, Depends, Header, HTTPException, status

from app.core.config import Settings, get_settings
from app.core.logging import get_logger
from app.core.observability import bind_request_id, clear_request_context
from app.models.schemas import AnalysisRequest, AnalysisResult
from app.services.claude_client import ClaudeClient
from app.services.gemini_client import GeminiClient
from app.services.orchestrator import Orchestrator

log = get_logger(__name__)
router = APIRouter(tags=["analyze"])


def _verify_token(
    settings: Settings,
    provided: str | None,
) -> None:
    """Constant-time compare the inbound token against the env."""
    if settings.internal_api_token is None:
        log.error("internal_api_token_unconfigured")
        raise HTTPException(status_code=503, detail="Service not configured.")
    if not provided or not hmac.compare_digest(
        provided, settings.internal_api_token.get_secret_value()
    ):
        log.warning("internal_token_rejected")
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Unauthorized.")


def get_orchestrator(settings: Settings = Depends(get_settings)) -> Orchestrator:
    """Build the orchestrator once per request.

    The provider clients are constructed here so the per-request HTTPX
    timeouts are bound. Tests override this dependency with a fake.
    """
    gemini = GeminiClient(settings)
    claude = ClaudeClient(settings)
    return Orchestrator(settings=settings, gemini=gemini, claude=claude)


@router.post(
    "/analyze",
    response_model=AnalysisResult,
    summary="Run AI orchestration for a pet health analysis",
    status_code=status.HTTP_200_OK,
)
async def analyze(
    request: AnalysisRequest,
    settings: Settings = Depends(get_settings),
    orchestrator: Orchestrator = Depends(get_orchestrator),
    x_pawdoc_internal_token: str | None = Header(default=None),
    x_request_id: str | None = Header(default=None),
) -> AnalysisResult:
    _verify_token(settings, x_pawdoc_internal_token)

    request_id = x_request_id or request.request_id
    bind_request_id(request_id)
    try:
        log.info(
            "analyze_received",
            pet_species=request.pet.species,
            pet_breed=request.pet.breed,
            input_type=request.input_type,
            text_len=(len(request.text_description) if request.text_description else 0),
        )
        result = await orchestrator.analyze(request)
        log.info(
            "analyze_completed",
            triage_level=result.triage_level,
            tier_used=result.tier_used,
            model_used=result.model_used,
            confidence=result.confidence,
            cross_verify_disagreement=result.cross_verify_disagreement,
            ai_latency_ms=result.ai_latency_ms,
        )
        return result
    finally:
        clear_request_context()
